language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - gcc-4.9
            - g++-4.9
            - cmake
            - cmake-data
            - lcov
      env: C_COMPILER=gcc-4.9 CXX_COMPILER=g++-4.9 GTEST_COLOR=1

    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - gcc-5
            - g++-5
            - cmake
            - cmake-data
            - lcov
      env: C_COMPILER=gcc-5 CXX_COMPILER=g++-5 GTEST_COLOR=1

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - george-edison55-precise-backports
          packages:
            - clang-3.7
            - cmake
            - cmake-data
            - lcov
      env: C_COMPILER=clang-3.7 CXX_COMPILER=clang++-3.7 GTEST_COLOR=1

install:
  - gem install coveralls-lcov
  - lcov --version

script:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER .
  - make CC=$C_COMPILER CXX=$CXX_COMPILER
  - ctest --verbose

after_success:
  - |
    if [[ "$CXX_COMPILER" == "g++-5" ]]; then
      cd ${TRAVIS_BUILD_DIR}
      lcov --gcov-tool gcov-5 --directory . --capture --output-file coverage.info
      lcov --gcov-tool gcov-5 --remove coverage.info 'test/*' '/usr/*' '/gtest/*' --output-file coverage.info
      lcov --gcov-tool gcov-5 --list coverage.info
      coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
    fi

